# Informasi blog

title: "NQ LEGENDS"
author: "nurzamanberserker"
description: "Semua tentang game ada di Nq legends"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B %Y"

# Latar belakang

show_excerpts: true
show_frame: true
show_sidebar: false
minimal: false

# Menu disini

navigation:
  - {file: "index.html"}
  - {file: "README.md"}

external:
  - {title: Mail, icon: envelope, url: "mailto:master@mwns.my.id"}
  - {title: Github, icon: github, url: "https://github.com/nurzamanberserker/my-portfolio"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""
#  isso_domain: ""

plugins:
 - jekyll-feed
